### ISSUE TITLE
Wrong TS type without normalization.

### ISSUE THREAD

**Issue by sharifzadesina** [extractus/feed-extractor#115]
When `normalization` option is `false` the returned type `FeedData` is false.

I suggest we return a generic type like `Record<string, any>`.

**Comment by olsonpm** [comment]
@sharifzadesina I'm not great with typescript - do you have a suggestion on how to implement that in a type definition file rather than in typescript code ?

Seems to me the best way to implement this request would be to have separate functions since you can't always infer the runtime options type.  e.g. `extractRaw => Record<string, any>`
