### ISSUE TITLE
Support Get  favicon

### ISSUE THREAD

**Issue by jc955** [extractus/feed-extractor#125]
hi, can feed-extractor, oEmbed Extractor support crawling to favicon URL like article-extractor?

**Comment by ndaidong** [comment]
@kk7771 thank you for your suggestion. I see two reasons not to do so:
- `feed-extractor`  and `oembed-extractor` do not touch the HTML page where the article is presented. Therefore, another request will be needed to download. This is different from `article-extractor`, which has to download the HTML first.
- `feed-extractor` returns a list of news entries coming from the same website, so you only need to get favicon.ico for that website once. You can save it along with a list of RSS urls as static files, instead of dynamic fetching.

You can get website favicon with Google S2. Just give it a domain or the whole URL, it will provide you the favicon to display on your view, e.g:

- https://www.google.com/s2/favicons?domain=github.com
- https://www.google.com/s2/favicons?domain=x.com
