### ISSUE TITLE
RSS Results Structure Changes Depending on Normalization

### ISSUE THREAD

**Issue by JulianWebb** [extractus/feed-extractor#74]
Hello!

I am glad to have found your module, it looks like it will make handling feeds easy.

---

The structure of the results from fetching an RSS feed depends on if the `normalization` option is set.

If it is **false** then the object containing the feed items is called `item` and if it is **true** then it is called `entries`.

I do not know if this is intended behaviour, however the documentation doesn't mention it either way.

**Comment by ndaidong** [comment]
@JulianWebb thank you. When you don't use `normalization`, this lib will keep the structure as it is. That's is expected behaviour.

In real world, it's more complicate than you said, here is what I known:

- RSS uses tag name `item`, ATOM uses tag name `entry`
- `item` and `entry` can be an array or single object (when there is only one item)
- JSONFeed uses `items`. Despite the fact that it's plural, it can be single object too!

So I recommend to enable `normalization` option if you need something more consistent.

**Comment by JulianWebb** [comment]
If I enable normalization though, I lose data from the field because it gets stripped.

I understand that the names are different, I just think it makes sense to expand the documentation around the normalization option to inform people of this.

**Comment by ndaidong** [comment]
@JulianWebb I agree that it is better to described more clear. The documentation is quite sketchy, not fully telling the capabilities of this library :bell: 

Note that 2 methods `getExtraFeedFields` and `getExtraEntryFields` can help you get any  data from feeds when you need, similar to #66

**Comment by JulianWebb** [comment]
Do those methods stop the normalization from stripping HTML and CDATA?

**Comment by ndaidong** [comment]
@JulianWebb no, they don't stop normalizing, but allow to choose which content you want to pick from the original data and how you want to customize these pieces.
